name: Bug报告
description: Create a report to help us improve
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        如果你可以自己 Debug 并解决的话, 建议您直接提交 PR 或 描述解决方法, 非常感谢!
  - type: checkboxes
    id: verify_step
    attributes:
      label: Verify Steps
      description: |
        在提交之前, 请确认 / Please verify that you've followed these steps.
      options:
        - label: Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
          required: true
        - label: Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
          required: true
        - label: Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
          required: true
        - label: Meaningful 我提交的不是无意义的 催促更新或修复 请求
          required: true
  - type: input
    id: openclash_version
    attributes:
      label: OpenClash Version
      description: |
        OpenClash 版本号
      placeholder: "v0.45.16-beta"
    validations:
      required: true
  - type: dropdown
    id: bug_os
    attributes:
      label: Bug on Environment
      description: |
        发现问题所在的系统环境 / System Environment
      multiple: true
      options:
        - Official OpenWrt
        - Lean
        - Docker
        - Other
    validations:
      required: true
  - type: dropdown
    id: bug_platform
    attributes:
      label: Bug on Platform
      description: |
        发现问题所在的架构平台 / Platform
      multiple: true
      options:
        - Linux-386
        - Linux-amd64(x86-64)
        - Linux-amd64-v3(x86-64)
        - Linux-armv5
        - Linux-armv6
        - Linux-armv7
        - Linux-armv8
        - Linux-mips-hardfloat
        - Linux-mips-softfloat
        - Linux-mips64
        - Linux-mips64le
        - Linux-mipsle-softfloat
        - Linux-mipsle-hardfloat
        - Other
        - All
    validations:
      required: true
  - type: textarea
    id: reproduce_bug
    attributes:
      label: To Reproduce
      description: |
        复现此Bug的步骤 / How to reproduce?
    validations:
      required: true
  - type: textarea
    id: describe_bug
    attributes:
      label: Describe the Bug
      description: |
        对Bug本身清晰而简洁的描述 / Describe the Bug
    validations:
      required: true
  - type: textarea
    id: openclash_log
    attributes:
      label: OpenClash Log
      description: |
        在下方附上 OpenClash 调试日志 / OpenClash Debug Log
        隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息
    validations:
      required: true
  - type: textarea
    id: openclash_config
    attributes:
      label: OpenClash Config
      description: |
        在下方附上与Bug相关的系统配置、防火墙规则或环境变量 / System config
      render: shell
    validations:
      required: false
  - type: textarea
    id: excepted_behavior
    attributes:
      label: Expected Behavior
      description: |
        对预期修复后情况的清晰明了的描述 / Expected behavior
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        添加屏幕截图以帮助解释您的问题 / Screenshots
    validations:
      required: false
